spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties.hibernate:
      # 재시작 시 JPA Entity(DB 테이블 데이터)를 새로 생성할지 여부 (create:기존데이터 삭제 후 신규 생성, udpate:신규 데이터만 업데이트, none:아무 실행도 하지 않음)
      hbm2ddl.auto: update
      format_sql: true
      show_sql: true
      use_sql_comments: true
    generate-ddl: true
    open-in-view: false
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/study?serverTimezone=Asia/Seoul
    #    url: jdbc:mysql://j6d106.p.ssafy.io:3307/?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ssafy
    #      password: Ssafy6!
    flyway:
      enabled: false
    config:
      activate:
        on-profile: alpha
    servlet:
      multipart:
        file-size-threshold: 15MB
        # 프로젝트 환경의 upload 파일을 저장할 경로
        #          location: /home/dev/projects/ssafy/upload
        max-file-size: 100MB
        max-request-size: 100MB